- name: Install orientdb as a sysvinit service
  copy:
    remote_src: True
    src: "{{ orientdb_path }}/bin/orientdb.sh"
    dest: /etc/init.d/orientdb
    mode: a+x
  register: orientdb_sysvinit_unit
  when: ansible_facts.service_mgr == 'sysvinit'

- name: Install orientdb as a systemd service
  template:
    src: orientdb.service.j2
    dest: /etc/systemd/system/orientdb.service
    owner: root
    group: root
    mode: 400
  register: orientdb_systemd_unit
  when: ansible_facts.service_mgr == 'systemd'

- name: Reload systemd daemon
  systemd :
    name: orientdb
    enabled: yes
    daemon_reload: yes
  when: orientdb_service_unit is changed

- name: Launch orientdb service
  service:
    name: orientdb
    state: restarted
    enabled: yes
  when: (orientdb_sysvinit_unit is defined and orientdb_sysvinit_unit is changed) or (orientdb_systemd_unit and orientdb_systemd_unit is changed) or orientdb_force_install == True
