- name: Install orientdb as a systemd service
  template:
    src: orientdb.service.j2
    dest: /etc/systemd/system/orientdb.service
    owner: root
    group: root
    mode: 0400
  register: orientdb_service_unit

- name: Start service
  systemd :
    name: orientdb
    state: restarted
    enabled: yes
    daemon_reload: yes
  when: orientdb_service_unit is changed or orientdb_force_install
