---
- name: Prerequisites
  fail:
    msg: Versions 1.x of this role cannot handle OrientDB version < 3 installations.
  when: orientdb_version[:1] | int < 3

- name: Create orientdb group
  group:
    name: "{{ orientdb_group }}"
    state: present

- name: Create orientdb user
  user:
    name: "{{ orientdb_user }}"
    password: "{{ orientdb_user_password }}"
    group: "{{ orientdb_group }}"

- name: Create log directory
  file:
    path: "{{ orientdb_log_dir }}"
    state: directory
    owner: "{{ orientdb_user }}"
    group: "{{ orientdb_group }}"

- include: install.yml

- include: configure-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: configure-Debian.yml
  when: ansible_os_family == 'Debian'
