VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|  
  config.vm.box = "ubuntu/vivid64"

  config.vm.define "server1" do |server|
    server.vm.network "private_network", ip: "192.168.10.5"
    server.vm.provider :virtualbox do |vb|
      vb.name = "orientdb-1"
      vb.customize ["modifyvm", :id, "--cpus", "1"]
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end 
  end

  config.vm.define "server2" do |server|
    server.vm.network "private_network", ip: "192.168.10.6"
    server.vm.provider :virtualbox do |vb|
      vb.name = "orientdb-2"
      vb.customize ["modifyvm", :id, "--cpus", "1"]
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end

end
